### ISSUE TITLE
MarkdownLivePreviewSyntax.sublime-settings::"word_wrap": true not functioning

### ISSUE THREAD

**Issue by william-voyek** [math2001/MarkdownLivePreview#34]
I have added the `"word_wrap":true` setting to my syntax specific settings file but the preview is still not wrapping:

<img width="1072" alt="screenshot 2017-08-18 21 49 22" src="https://user-images.githubusercontent.com/989760/29483630-35511ba0-845f-11e7-9596-ee00fe8abe1d.png">

My settings file:
```
// These settings override both User and Default settings for the MarkdownLivePreviewSyntax syntax
{
    "show_tabs": true,
    "word_wrap": true
}
```

**Comment by wangray** [comment]
I have the same issue.

**Comment by bkarlson** [comment]
same, preview window not wrapping, a bit frustrating

**Comment by math2001** [comment]
Hum... Looked into it and it's a bit weird. Word wrap **is on**, it's just not wrapping properly.

Can you please do the following:

1. Open a preview window
2. click on the tab of the *preview* (if you press <kbd>ctrl+p</kbd>, it should open on the preview's pane)
3. Go into the `View` menu, and see if the `Word Wrap` option is enabled.

In my case, it is, but wrapping the Phantom (the preview thing) doesn't seem to take into account the minimap, and to wrap properly at all.

**Comment by bkarlson** [comment]
partial fix via custom css:
```
body {
    font-family: Verdana, "Open Sans", sans-serif;
    font-size: 13px;
    width:550px; /* adjust to your liking */
}

```

**Comment by bkarlson** [comment]
Sorry, @math2001 , just noticed your prompt response. Yes, word wrap is enabled for both windows, still no avail:
![image](https://user-images.githubusercontent.com/30080507/31009801-ddbf5844-a532-11e7-81aa-bbbce260f69d.png)

**Comment by math2001** [comment]
So, I guess that's Sublime's problem, with the `Phantom`. I'll look into it a bit more (I feel like images and `pre` tags might cause those bugs...)

**Comment by bkarlson** [comment]
Yes, you're right, it's overly wide images & unbroken lines within `tt` or `code` elements that cause whole document to become too wide. 
Easy fix for `img` via custom css:
```css
img {width:680px}
```
(distorts images, but still)
Yet no fix for code blocks, minihtml is way too limited in my view. See if you can come up with a better idea

**Comment by math2001** [comment]
Does it work? `width` isn't mentionned in the [minihtml](https://www.sublimetext.com/docs/3/minihtml.html) reference...

Did you try `witdth: 100%` and/or `max-width: 100%`?

**Comment by bkarlson** [comment]
Yep, tried 100%, seems like it interpreted as 100px 😬 
See my current CSS below, at least it contains overall doc width within my panel width, but long lines in`<tt>` still remain unbroken and hang like hell, see below. Images are distorted, as `height:auto` is ignored, but at least I can see them w/o scrolling when width is fixed.

```css

body {
    font-family: Verdana, "Open Sans", sans-serif;
    font-size: 13px;
   background-color:white;
   width: 680px;
}

html {
   background-color:white;
    --light-bg: color(var(--background) blend(#eee 85%));
    --very-light-bg: color(var(--background) blend(#eee 92%));
}

img {width:680px}
```
![image](https://user-images.githubusercontent.com/30080507/31057759-0a6b66b8-a712-11e7-8527-3e71237f8c05.png)
![image](https://user-images.githubusercontent.com/30080507/31057760-0a6d80a6-a712-11e7-9828-22c961f8fac4.png)
